config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: 'search#index', as: :search

  resources :customers do
    get :price
  end
  resources :deliveries
  resources :invoices
  resources :products, except: :index do
    get '(/:group)' => :index, on: :collection, as: ''
  end
  resources :sellers, except: :show
  resources :reports do
    get :free, on: :collection
  end
  resources :statistics do
    get :preview, on: :collection
    get :overview, on: :collection
    get :customers, on: :collection
  end

  get 'dashboard' => 'dashboard#index'
  root to: 'dashboard#show'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, except: :show
  after_action :verify_authorized, except: :show

  def index
    authorize :dashboard
  end

  def show
    redirect_to  user_signed_in? ? dashboard_url : new_user_session_url
  end
end

app/views/dashboard/index.html.slim
h1 Startseite
/= react_component('Dashboard', deliveries: @deliveries.as_json(only: %i(id number date)) )

.row
  .col-md-4
    = link_to t('deliveries.index.new_delivery'), new_delivery_url, class: 'btn btn-primary btn-block btn-lg'
    h3 Letzte Lieferungen
    table.table.table-hover.table-condensed.table-clickable
      tbody
        - Delivery.includes(:customer).order(date: :desc, number: :desc).limit(15).each do |delivery|
          tr data = {url: url_for(delivery)} class=(delivery.pending? ? 'danger' : '')
            td = fa_icon delivery.on_account ? 'list-alt' : 'eur'
            td = delivery.number
            td = ldate delivery.date
            td = delivery.customer.name
  .col-md-4
    h3 Letzte Rechnungen
    table.table.table-hover.table-condensed.table-clickable
      tbody
        - Invoice.includes(:customer).order(number: :desc).limit(15).each do |invoice|
          tr data = {url: url_for(invoice)}
            td = invoice.number
            td = ldate invoice.date
            td = invoice.customer.name
  .col-md-4
    - open_deliveries = Delivery.pending
    = link_to t('.write_invoices'), new_invoice_url, class: 'btn btn-primary btn-block btn-lg' if open_deliveries.any?
    h3
      => open_deliveries.count
      |  offene Lieferscheine

    - if open_deliveries.any?
      table.table.table-hover.table-condensed.table-clickable
        tbody
          - open_deliveries.each do |delivery|
            tr data = {url: url_for(delivery)}
            td = delivery.number
            td = ldate delivery.date
            td = delivery.customer.name