config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: 'search#index', as: :search

  resources :customers do
    get :price
  end
  resources :deliveries
  resources :invoices
  resources :products, except: :index do
    get '(/:group)' => :index, on: :collection, as: ''
  end
  resources :sellers, except: :show
  resources :reports do
    get :free, on: :collection
  end
  resources :statistics do
    get :preview, on: :collection
    get :overview, on: :collection
    get :customers, on: :collection
  end

  get 'dashboard' => 'dashboard#index'
  root to: 'dashboard#show'
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  validates :name, presence: true

  attr_reader :result

  TIME_RANGES = %w(week month quart year).flat_map do |period|
    %w(this last).map { |this_last| "#{this_last}_#{period}" }
  end + ['custom']
  GROUPING    = %w(region customer_category product_category time time_year seller)
  FILTERS     = %w(regions customer_categories product_categories)
  SUMS        = %w(content net tax)
  SUM_TYPES   = %i(content net tax net_content)

  def time_range_relative
    time_range['relative']
  end

  %w(x y).each { |dim| define_method("grouping_#{dim}") { grouping[dim] } }

  FILTERS.each { |filter_name| define_method(filter_name) { filter[filter_name] || [] } }

  def labels_for(x_or_y)
    hash = (x_or_y == :x) ? @result[:content] : @result
    hash.keys.reject { |key| key.is_a? Symbol }.sort
  end

  def label_for(x_or_y, label)
    case grouping[x_or_y.to_s]
      when 'time' then I18n.t('date.abbr_month_names')[label]
      when 'time_year' then label.to_i
    else label
    end
  end

  def items_scope(only: nil)
    scope = DeliveryItem
      .joins(:product, delivery: [:customer, :seller])
      .where('deliveries.date >= ?', start_date)
      .where('deliveries.date <= ?', end_date)
    scope = if only
      scope.group(group_option(only))
    else
      scope.group(group_option(:y), group_option(:x))
    end
    if regions.any? || customer_categories.any?
      customer_scope = Customer
      customer_scope = customer_scope.where(region: regions) if regions.any?
      customer_scope = customer_scope.where(category: customer_categories) if customer_categories.any?
      scope          = scope.where(delivery: Delivery.where(customer: customer_scope))
    end
    if product_categories.any?
      scope = scope.where(product: Product.where(category: product_categories))
    end
    scope
  end

  def calculate!
    @result = sums_for(:x)
    items_scope.sum(sum_option).each do |(y, x), value|
      @result[y] ||= {}
      @result[y][x] = cast_val value
    end
    y_sums = sums_for(:y)
    @result.each do |y_label, row|
      SUM_TYPES.each { |sum_type| row[sum_type] = y_sums[sum_type][y_label] }
    end
    @result
  end

  def sums_for(x_or_y)
    sums = {
      content:     items_scope(only: x_or_y).sum(sum_option(type: 'content')),
      net:         items_scope(only: x_or_y).sum(sum_option(type: 'tax')),
      tax:         {},
      net_content: {},
    }
    sums[:net].each do |label, value|
      sums[:net][label] = cast_val value, type: 'net'
      sums[:tax][label] = cast_val value, type: 'tax'
      sums[:net_content][label] = (sums[:net][label] / sums[:content][label]) if sums[:content][label] != 0
    end
    %i(content net tax).each { |sum_type| sums[sum_type][:total] = sums[sum_type].values.sum }
    sums
  end

  def cast_val(value, type: sums_of)
    return value if type == 'content'
    value = Money.new(value)
    return value.exchange_to('EURNET') if type == 'net'
    value.exchange_to('EU4TAX').exchange_to('EURTAX')
  end

  def group_option(x_or_y)
    case grouping[x_or_y.to_s]
      when 'region'            then 'customers.region'
      when 'customer_category' then 'customers.category'
      when 'product_category'  then 'products.category'
      when 'time'              then 'extract(month from deliveries.date)'
      when 'time_year'         then 'extract(year from deliveries.date)'
      when 'seller'            then 'sellers.short'
    end
  end

  def sum_option(type: sums_of)
    return 'count * products.content' if type == 'content'
    'count * unit_price_cents'
  end

  def start_date
    date_range.first
  end

  def end_date
    date_range.last
  end

  def date_range
    return [custom_date('start'), custom_date('end')] if time_range_relative == 'custom'
    today      = Date.current
    last_week  = 1.week.ago.to_date
    last_month = 1.month.ago.to_date
    last_quart = 3.month.ago.to_date
    last_year  = 1.year.ago.to_date
    case time_range_relative
      when 'this_week'  then [today.     beginning_of_week,    today.     end_of_week]
      when 'last_week'  then [last_week. beginning_of_week,    last_week. end_of_week]
      when 'this_month' then [today.     beginning_of_month,   today.     end_of_month]
      when 'last_month' then [last_month.beginning_of_month,   last_month.end_of_month]
      when 'this_quart' then [today.     beginning_of_quarter, today.     end_of_quarter]
      when 'last_quart' then [last_quart.beginning_of_quarter, last_quart.end_of_quarter]
      when 'this_year'  then [today.     beginning_of_year,    today.     end_of_year]
      when 'last_year'  then [last_year. beginning_of_year,    last_year. end_of_year]
    end
  end

  def custom_date(start_or_end)
    Date.parse(time_range["#{start_or_end}_date"])
  end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  before_action :set_statistic, only: %i[show edit update destroy]

  def index
    authorize Statistic
    @statistics = Statistic.all
  end

  def show
    @statistic.calculate!
  end

  def overview
    authorize Statistic
    today       = Date.current
    @start_date = get_date :start_date, today.beginning_of_year
    @end_date   = get_date :end_date,   today

    @statistics = Setting.statistics.map do |stat|
      SalesStatistic.new stat.merge(date: @start_date..@end_date).symbolize_keys
    end
  end

  def customers
    authorize Statistic
    today       = Date.current
    @start_date = get_date :start_date, today.beginning_of_year
    @end_date   = get_date :end_date,   today

    @product_group = 'PG'

    @customers =
      DeliveryItem.joins(delivery: :customer)
        .where('deliveries.date' => @start_date..@end_date, product_group: @product_group, has_content: true)
        .group(:customer_id, 'customers.name')
        .select('customers.name', 'sum(total_content_in_g / 1000) as total_kg', 'sum(total_price_cents) as sum_price')
        .order('total_kg DESC')
  end

  def new
    authorize Statistic
    @statistic = Statistic.new time_range: { relative: 'last_year' },
                               grouping: { x: 'time', y: 'customer_category' }
  end

  def edit; end

  def create
    authorize Statistic
    @statistic = Statistic.new statistic_params

    if @statistic.save
      redirect_to @statistic, notice: t(:created, model: Statistic.model_name.human)
    else
      render :new
    end
  end

  def update
    if @statistic.update statistic_params
      redirect_to @statistic, notice: t(:updated, model: Statistic.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @statistic.destroy
    redirect_to statistics_url, notice: t(:destroyed, model: Statistic.model_name.human)
  end

  def preview
    authorize Statistic
    @statistic = Statistic.new statistic_params
    @statistic.calculate!
    render partial: 'table', layout: false, locals: { statistic: @statistic }
  rescue StandardError
    render text: ''
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_statistic
    @statistic = Statistic.find params[:id]
    authorize @statistic
  end

  # Only allow a trusted parameter "white list" through.
  def statistic_params
    p = params.require(:statistic).permit(:name, :time_range_relative, :start_date, :end_date,
                                          :grouping_x, :grouping_y, :sums_of,
                                          regions: [], customer_categories: [], product_categories: [])
    p[:time_range] = {
      relative:   p.delete(:time_range_relative),
      start_date: p.delete(:start_date),
      end_date:   p.delete(:end_date),
    }

    p[:grouping] = {}
    p[:grouping][:x] = p.delete :grouping_x
    p[:grouping][:y] = p.delete :grouping_y

    p[:filter] = {}
    p[:filter][:regions]             = p.delete(:regions).reject(&:blank?)
    p[:filter][:customer_categories] = p.delete(:customer_categories).reject(&:blank?)
    p[:filter][:product_categories]  = p.delete(:product_categories).reject(&:blank?)
    p
  end

  def get_date(date, default)
    params[date] ? Date.parse(params[date]) : default
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper

  def time_range_collection
    Statistic::TIME_RANGES.each_with_object({}) do |range, hash|
      hash[t("statistic.time_range.#{range}")] = range
    end
  end

  def grouping_collection
    Statistic::GROUPING.each_with_object({}) do |group_name, hash|
      hash[t("statistic.grouping.#{group_name}")] = group_name
    end
  end

  def sum_collection
    Statistic::SUMS.each_with_object({}) do |sum_name, hash|
      hash[t("statistic.sum.#{sum_name}")] = sum_name
    end
  end
end

app/views/statistics/_form.html.slim
= simple_form_for(@statistic) do |f|
  = f.error_notification

  .form-inputs.hidden-print
    .row
      .col-md-4
        = f.input :time_range_relative, as: :select, collection: time_range_collection, include_blank: false
        = f.input :start_date, input_html: { class: 'date' }
        = f.input :end_date, input_html: { class: 'date' }
      .col-md-4
        - filter_options = { multiple: true, class: 'select2', data: { placeholder: 'Alle' } }
        = f.input :regions, collection: Setting.customer_regions, input_html: filter_options
        = f.input :customer_categories, collection: Setting.customer_categories, input_html: filter_options
        = f.input :product_categories, collection: Setting.product_categories, input_html: filter_options
      .col-md-4
        = f.input :grouping_y, collection: grouping_collection, include_blank: false
        = f.input :grouping_x, collection: grouping_collection, include_blank: false
        = f.input :sums_of, as: :select, collection: sum_collection, include_blank: false

  .form-actions.row.hidden-print
    .col-md-3.col-md-offset-8 = f.input :name, label: false, placeholder: 'Name'
    .col-md-1 = f.submit t(:save), class: 'btn btn-primary'

.preview

coffee:
  $ -> new StatisticForm()

app/views/statistics/_stats_row.html.slim
tr
  td = label
  /td
    | EUR
    br
    span.content kg
  - stat.product_categories_content.each do |prod_cat|
    - prod_cat_data = prod_cats[prod_cat]
    td.price
      span.content = prod_cat_data && number_with_delimiter(prod_cat_data[:total_content])
    td.price = prod_cat_data && nontax_price(prod_cat_data[:total_price])
  td.price
    span.content = number_with_delimiter prod_cats[:sum][:total_content]

  /- Setting.product_cats['fees'].each do |prod_cat|
    td.price
      - if (prod_cat_data = prod_cats[prod_cat])
        = nontax_price prod_cat_data[:total_price]
  td.price
    - sum = Setting.product_cats['fees'].map { |prod_cat| (prod_cats[prod_cat] && prod_cats[prod_cat][:total_price]) || Money.new(0) }.sum
    - if sum > Money.new(0)
      - title = stat.product_categories_fees.map { |cat| prod_cats[cat] ? "#{cat}: #{prod_cats[cat][:total_price].to_f.round(2)}" : nil }
      = nontax_price(sum, title: title.compact.join(', '))
  td.price = nontax_price prod_cats[:sum][:total_price]
  td.price = tax_price prod_cats[:sum][:total_price]

app/views/statistics/_table.html.slim
- result   = statistic.result
- x_labels = statistic.labels_for(:x)
- y_labels = statistic.labels_for(:y)
table.table.table-striped.table-hover.statistics
  thead
    tr
      th
      - x_labels.each do |x|
        th.price = statistic.label_for(:x, x)
      - Statistic::SUM_TYPES.each do |sum_type|
        th = t("statistic.sum.#{sum_type}")
  tbody
    - y_labels.each do |y|
      - row = result[y]
      tr
        th = statistic.label_for(:y, y)
        - x_labels.each do |x|
          td.price = display_price_or_content(row[x], statistic.sums_of) if row[x]
        - Statistic::SUM_TYPES.each do |sum_type|
          th.price = display_price_or_content row[sum_type], sum_type
  tfoot
    - Statistic::SUM_TYPES.each_with_index do |sum_type, index|
      tr
        th = t("statistic.sum.#{sum_type}")
        - x_labels.each do |x|
          th.price = display_price_or_content result[sum_type][x], sum_type
        th.price colspan=(index + 1) = display_price_or_content result[sum_type][:total], sum_type
        td colspan=(4 - index)

sass:
  table.statistics
    th, td
      white-space: nowrap
    th
      font-size: small
    td
      font-size: smaller

app/views/statistics/customers.html.slim
.row
  .col-md-6
    h1 Kundenstatistik
  .col-md-6
    .search-form
      form.form-inline
        .form-group
          label.string.required.control-label> for="start-date" Vom
          input#start-date.form-control.date> type="text" name="start_date" value=@start_date
          label.string.required.control-label> for="end-date" bis
          input#end-date.form-control.date> type="text" name="end_date" value=@end_date

.table-responsive
  table.table.table-hover.table-striped.table-condensed.table-bordered
    thead
      tr
        th Kunde
        th.price kg
        th.price Netto

    tbody
      - @customers.each do |customer|
        tr
          td = customer.name
          td.price = customer.total_kg
          td.price = nontax_price Money.new(customer.sum_price, 'EU4NET')

coffee:
  $ ->
    $('.search-form input').off('change').change(-> $('.search-form form').submit())

app/views/statistics/edit.html.slim
.page-header
  h2
    => @statistic.name
    small = Statistic.model_name.human

= render 'form'

app/views/statistics/index.html.slim
.page-header
  = link_to statistics_path(format: :csv), id: 'export-csv-button', class: 'btn btn-default' do
    span.glyphicon.glyphicon-export
    =< t(:export)
  = link_to new_statistic_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    =< t(:new)
  h2
    => @statistics.count
    = Statistic.model_name.human count: @statistics.count

.table-responsive
  table.table.table-striped.table-bordered.table-hover.table-clickable
    thead
      tr
        th = Statistic.human_attribute_name(:name)
        th = Statistic.human_attribute_name(:time_range_relative)
        th = Statistic.human_attribute_name(:grouping_y)
        th = Statistic.human_attribute_name(:grouping_x)
        th = Statistic.human_attribute_name(:filter)
        th = Statistic.human_attribute_name(:sums_of)
    tbody
      - @statistics.each do | statistic |
        tr data = {url: url_for(statistic)}
          td = statistic.name
          td = statistic.time_range_relative
          td = statistic.grouping_y
          td = statistic.grouping_x
          td = statistic.filter
          td = statistic.sums_of

app/views/statistics/new.html.slim
.page-header
  h2 = t(".title")

= render 'form'

app/views/statistics/overview.html.slim
.row
  .col-md-6
    h1 Statistik
  .col-md-6
    .search-form
      form.form-inline
        .form-group
          label.string.required.control-label> for="start-date" Vom
          input#start-date.form-control.date> type="text" name="start_date" value=@start_date
          label.string.required.control-label> for="end-date" bis
          input#end-date.form-control.date> type="text" name="end_date" value=@end_date

- @statistics.each do |stat|
  h4 = stat.name

  - result = stat.results
  - sums = result.delete(:sums)
  .table-responsive
    table.table.table-hover.table-striped.table-condensed.table-bordered.statistic
      thead
        tr
          th Kategorie
          /th
          - stat.product_categories_content.each do |prod_cat|
            th.price colspan=2 = prod_cat
          th.price kg ges
          /- Setting.product_cats['fees'].each do |prod_cat|
            th.price = prod_cat
          th.price Gebühren
          th.price Netto
          th.price Brutto

      tbody
        - result.each do |cust_cat, prod_cats|
          = render 'stats_row', label: cust_cat, prod_cats: prod_cats, stat: stat
      tfoot
        = render 'stats_row', label: 'Summe', prod_cats: sums, stat: stat

coffee:
  $ ->
    $('.search-form input').off('change').change( -> $('.search-form form').submit())


sass:
  table.statistic
    tfoot
      td
        font-weight: bold
    td, th
      padding: 3px !important
    span.content
      font-style: italic
      color: blue

app/views/statistics/show.html.slim
.page-header
  /= link_to statistics_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    =< t(:list)
  = link_to edit_statistic_path(@statistic), class: 'btn btn-primary' do
    span.glyphicon.glyphicon-pencil
    =< t(:edit)
  => link_to @statistic, method: :delete, data: { confirm: t(:confirm_delete, model: Statistic.model_name.human) }, class: 'btn btn-danger' do
    span.glyphicon.glyphicon-remove
    =< t(:delete)
  h2
    => @statistic.name
    small = Statistic.model_name.human

.row
  .col-md-3
    label #{t('statistic.grouping.' + @statistic.grouping_y)} -> #{t('statistic.grouping.' + @statistic.grouping_x)}
  .col-md-3
    label
      => t('statistic.time_range.' + @statistic.time_range['relative'])
      small> #{ldate @statistic.start_date} - #{ldate @statistic.end_date}
  .col-md-1
    label => t('statistic.sum.' + @statistic.sums_of)
.row
  .col-md-12
    label> Filter:
    - if @statistic.regions.any?
      - @statistic.regions.each do |filter|
        span.label.label-info> = filter
    - if @statistic.customer_categories.any?
      - @statistic.customer_categories.each do |filter|
        span.label.label-warning> = filter
    - if @statistic.product_categories.any?
      - @statistic.product_categories.each do |filter|
        span.label.label-primary> = filter

= render 'table', statistic: @statistic