config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: 'search#index', as: :search

  resources :customers do
    get :price
  end
  resources :deliveries
  resources :invoices
  resources :products, except: :index do
    get '(/:group)' => :index, on: :collection, as: ''
  end
  resources :sellers, except: :show
  resources :reports do
    get :free, on: :collection
  end
  resources :statistics do
    get :preview, on: :collection
    get :overview, on: :collection
    get :customers, on: :collection
  end

  get 'dashboard' => 'dashboard#index'
  root to: 'dashboard#show'
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :delivery_items
  has_many :prices

  validates :number, presence: true, uniqueness: true

  scope :in_stock, -> { where in_stock: true }

  register_currency :eu4net
  monetize :price_cents

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    authorize Product
    @product_group = params[:group] || Setting.product_groups.first
    @products      = Product.where(group: @product_group).order(:category, :number)
  end

  def show
  end

  def new
    authorize Product
    @product = Product.new
  end

  def edit
  end

  def create
    authorize Product
    @product = Product.new product_params

    if @product.save
      redirect_to products_url, notice: t(:created, model: Product.model_name.human)
    else
      render :new
    end
  end

  def update
    if @product.update product_params
      redirect_to products_url, notice: t(:updated, model: Product.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: t(:destroyed, model: Product.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find params[:id]
    authorize @product
  end

  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product)
      .permit(:number, :size, :name, :content, :unit, :category, :in_stock, :group)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= simple_form_for(@product) do |f|
  = f.error_notification

  section
    .col-md-6
      .form-inputs
        = f.input :number
        = f.input :category, collection: Setting.product_categories
        = f.input :group, collection: Setting.product_groups
        = f.input :name
        = f.input :content
        = f.input :unit
        /.row
          .col-md-8 = f.input :price
          .col-md-4 = f.input :price_currency, collection: Money.currencies, include_blank: false
        = f.input :in_stock

  section.action-buttons
    .col-md-12
      .pull-right
        => link_to t(:cancel), 'javascript: window.history.back();', class: 'btn btn-default'
        = f.submit t(:save), class: 'btn btn-primary'

app/views/products/edit.html.slim
- title_for @product, :number
.page-header
  h2
    => @product.name
    small = Product.model_name.human

= render 'form'

app/views/products/index.html.slim
- title_for Product
.page-header
  = new_link new_product_url
  h2
    => @products.count
    = Product.model_name.human count: @products.count


ul.nav.nav-tabs
  - Setting.product_groups.each do |group|
    li class=('active' if @product_group == group)
      = link_to group, products_url(group: group)


- [true, false].each do |in_stock|
  - products   = @products.where(in_stock: in_stock)
  - categories = products.pluck(:category).uniq.sort

  h3 = in_stock ? 'Bestandsartikel' : 'Gebühren'
  .table-responsive
    table.table.table-striped.table-bordered.table-hover.table-clickable
      thead
        tr
          th = Product.human_attribute_name(:category)
          th = Product.human_attribute_name(:number)
          th = Product.human_attribute_name(:name)
          - if in_stock
            th.price = Product.human_attribute_name(:content)
            th       = Product.human_attribute_name(:unit)
          th.price Preise
          th.price Lieferungen
      tbody
        - products.order(:category, :number).each do |product|
          tr data = {url: edit_product_url(product)}
            td = product.category
            td = product.number
            td = product.name
            - if in_stock
              td.price = number_to_human product.content
              td = product.unit
            td.price = product.prices.count
            td.price = product.delivery_items.count

app/views/products/new.html.slim
- title_for Product, :new
.page-header
  h2 = t('.title')

= render 'form'

app/views/products/show.html.slim
- title_for @product, :number
.page-header
  = list_link products_url
  = edit_link edit_product_path(@product)
  = delete_link @product
  h2
    => @product.name
    small = Product.model_name.human

.row
  .col-md-6 = panel_box title: Product.model_name.human do
    .row
      label.col-md-4 => Product.human_attribute_name(:number)
      .col-md-8 = @product.number
    .row
      label.col-md-4 => Product.human_attribute_name(:category)
      .col-md-8 = @product.category
    .row
      label.col-md-4 => Product.human_attribute_name(:name)
      .col-md-8 = @product.name
    .row
      label.col-md-4 => Product.human_attribute_name(:content)
      .col-md-8
        => @product.content
        = @product.unit
    .row
      label.col-md-4  => Product.human_attribute_name(:in_stock)
      .col-md-8 = bool_icon @product.in_stock