config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: 'search#index', as: :search

  resources :customers do
    get :price
  end
  resources :deliveries
  resources :invoices
  resources :products, except: :index do
    get '(/:group)' => :index, on: :collection, as: ''
  end
  resources :sellers, except: :show
  resources :reports do
    get :free, on: :collection
  end
  resources :statistics do
    get :preview, on: :collection
    get :overview, on: :collection
    get :customers, on: :collection
  end

  get 'dashboard' => 'dashboard#index'
  root to: 'dashboard#show'
end

app/models/report.rb
class Report < ActiveRecord::Base

  validates :name, :product_group, presence: true

  attr_accessor :start_date, :end_date

  scope(:in_menu, -> { where in_menu: true })

  def products
    @products ||= Product.where(group: product_group, in_stock: true).order(:number).all
  end

  def days
    ensure_date_range
    Delivery.joins(:items).uniq.order(:date)
      .where('delivery_items.product_group' => product_group, date: @start_date..@end_date).pluck(:date)
  end

  def daily_reports
    days.map { |day| DailyReport.new day, product_group, content_categories: content_product_categories }
  end

  def sum_report
    ensure_date_range
    DailyReport.new @start_date..@end_date, product_group, content_categories: content_product_categories
  end

  private

  def ensure_date_range
    raise 'start and end date must be set before running this action' unless start_date.is_a?(Date) && end_date.is_a?(Date)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    authorize Report
    @reports = Report.all
  end

  def show
    @report.start_date = get_date :start_date, Date.current.beginning_of_week
    @report.end_date   = get_date :end_date,   Date.current

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(@report)
        send_data pdf.render, filename: pdf.filename, type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  def free
    authorize Report
    @report = DeliveryReport.new filter: { date: 1.month.ago..Date.current }
  end

  def new
    authorize Report
    @report = Report.new
  end

  def edit; end

  def create
    authorize Report
    @report = Report.new report_params

    if @report.save
      redirect_to @report, notice: t(:created, model: Report.model_name.human)
    else
      render :new
    end
  end

  def update
    if @report.update report_params
      redirect_to @report, notice: t(:updated, model: Report.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_url, notice: t(:destroyed, model: Report.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find params[:id]
    authorize @report
  end

  # Only allow a trusted parameter "white list" through.
  def report_params
    allowed = [
      :name, :in_menu, :product_group, product_categories: [], content_product_categories: []
    ]
    params.require(:report).permit(allowed).tap do |p|
      p[:product_categories].reject!(&:blank?)
      p[:content_product_categories].reject!(&:blank?)
    end
  end

  def get_date(date, default)
    params[date] ? Date.parse(params[date]) : default
  end
end

app/views/reports/_form.html.slim
= simple_form_for(@report) do |f|
  = f.error_notification

  .row
    .col-md-6
      = f.input :name
      = f.input :in_menu
    .col-md-6
      - category_select_options = { collection: Setting.product_categories, input_html: { class: 'select2', multiple: true } }
      = f.input :product_group, collection: Setting.product_groups, include_blank: false
      = f.input :product_categories,         category_select_options
      = f.input :content_product_categories, category_select_options

  .form-actions
    = f.button :submit

app/views/reports/_sum_row.html.slim
tr class=css_class
  td = fa_icon on_account ? 'list-alt' : 'eur' unless on_account.nil?
  th colspan=2 = label
  - count_sums = daily_report.count_sums on_account: on_account
  - @report.products.each do |product|
    th.price = count_sums[product.number]
  - content_sums = daily_report.content_sums on_account: on_account
  - cat_sums = @report.content_product_categories.map { |cat| content_sums[cat] }
  - cat_sums.each do |sum|
    th.content = number_with_delimiter sum
  th.content = number_with_delimiter cat_sums.compact.sum

  - total_price = daily_report.total_price(on_account: on_account)
  th.price = nontax_price total_price
  th.price = tax_price total_price

app/views/reports/edit.html.slim
.page-header
  h2
    => @report.name
    small = Report.model_name.human

= render 'form'

app/views/reports/free.html.slim
h1
  => @report.count
  |  results

.row
  .col-md-4
    label Filters
    br
    = @report.filter
  .col-md-4
    label Groups
    br
    = @report.groups
  .col-md-4
    label Sums
    br
    = @report.sums
br
table.table.table-condensed.table-bordered.table-hover
  thead
    tr
      - for field in @report.groups
        th = field
      - for field in @report.sums
        th.price = field
  tbody
    - @report.rows.each do |row|
      tr
        - for field in @report.groups
          td = row.send field
        - for field in @report.sums
          td.price = row.send field

app/views/reports/index.html.slim
.page-header
  = link_to reports_path(format: :csv), id: 'export-csv-button', class: 'btn btn-default' do
    span.glyphicon.glyphicon-export
    =< t(:export)
  = link_to new_report_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    =< t(:new)
  h2
    => @reports.count
    = Report.model_name.human count: @reports.count

.table-responsive
  table.table.table-striped.table-bordered.table-hover.table-clickable
    thead
      tr
        th = Report.human_attribute_name(:name)
        th = Report.human_attribute_name(:product_categories)
        th = Report.human_attribute_name(:products)
        th = Report.human_attribute_name(:in_menu)
    tbody
      - @reports.each do | report |
        tr data = {url: edit_report_url(report)}
          td = report.name
          td = report.product_categories.join(', ')
          td = report.products.count
          td = bool_icon report.in_menu

app/views/reports/show.html.slim
.page-header
  h2 => @report.name

.search-form
  form.form-inline
    .form-group
      label.string.required.control-label> for="start-date" Vom
      input#start-date.form-control.date> type="text" name="start_date" value=@report.start_date
      label.string.required.control-label> for="end-date" bis
      input#end-date.form-control.date> type="text" name="end_date" value=@report.end_date
      = pdf_link report_url(@report, format: :pdf, start_date: @report.start_date, end_date: @report.end_date)

table.table.table-condensed.table-striped.table-hover
  - @report.daily_reports.each do |daily_report|
    thead
      tr
        th colspan=(6 + @report.products.count + @report.content_product_categories.count)
          h3 = ldate daily_report.day, format: '%a %d.%m.%Y'
    tbody
      tr.header-row
        td
        th Lieferschein
        th Kunde
        - @report.products.each do |product|
          th.price = product.number
        - @report.content_product_categories.each do |cat|
          th.content = cat
        th.content kg ges
        th.price Netto
        th.price Brutto
      - daily_report.deliveries.each do |delivery|
        tr
          td = fa_icon delivery.on_account ? 'list-alt' : 'eur'
          td = link_to delivery.number, delivery.delivery
          td = delivery.customer
          - products = delivery.products
          - @report.products.each do |product|
            td.price = products[product.number]
          - @report.content_product_categories.each do |cat|
            td.content = delivery.cat_content[cat]
          th.content = delivery.total_content
          td.price = nontax_price(delivery.total_price)
          td.price =    tax_price(delivery.total_price)

      - [false, true, nil].each do |on_account|
        - label = on_account ? 'auf Rechnung' : 'Bareinnahmen'
        - label = ldate(daily_report.day, format: '%a %d.%m.%Y') if on_account.nil?
        = render 'sum_row', daily_report: daily_report, css_class: 'on-account-sum-row', label: label, on_account: on_account

  tfoot
    - sum_report = @report.sum_report
    tr
      th colspan=(6 + @report.products.count + @report.content_product_categories.count)
    - [false, true, nil].each do |on_account|
      - label = on_account ? 'auf Rechnung' : 'Bareinnahmen'
      - label = 'Gesamtsumme' if on_account.nil?
      = render 'sum_row', daily_report: sum_report, css_class: 'total-sum-row', label: label, on_account: on_account

coffee:
  $ ->
    $('.search-form input').off('change').change( -> $('.search-form form').submit())

sass:
  tr
    &.header-row
      border: 2px solid grey
    &.on-account-sum-row
      background-color: #ccc !important
      font-size: 14px
    &.day-sum-row
      background-color: #ccc !important
      /*border: 1px solid grey*/
      font-size: 16px
    &.total-sum-row
      border: 2px solid grey
      font-size: 18px

app/views/reports/stats.html.slim
h1 Statistik

- @statistics.each do |stat|
  h4 = stat.name

  - result = stat.results
  - sums = result.delete(:sums)
  .table-responsive
    table.table.table-hover.table-striped.table-condensed.table-bordered.statistic
      thead
        tr
          th Kategorie
          th
          - stat.product_categories_content.each do |prod_cat|
            th.price = prod_cat
          th.price kg ges
          - stat.product_categories_fees.each do |prod_cat|
            th.price = prod_cat
          th.price Netto
          th.price Brutto

      tbody
        - result.each do |cust_cat, prod_cats|
          = render 'stats_row', label: cust_cat, prod_cats: prod_cats, stat: stat
      tfoot
        = render 'stats_row', label: 'Summe', prod_cats: sums, stat: stat

sass:
  table.statistic
    tfoot
      td
        font-weight: bold
    td, th
      padding: 3px !important
    span.content
      font-style: italic
      color: blue